# Generated by Django 5.2.7 on 2025-10-25 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackAttributeEnum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrackType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tracks', to='locations.location')),
                ('track_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tracks', to='tracks.tracktype')),
            ],
        ),
        migrations.CreateModel(
            name='TrackAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attributes', to='tracks.track')),
                ('attribute_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tracks.trackattributeenum')),
            ],
        ),
    ]
