# Generated by Django 5.2.7 on 2025-10-29 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_profile_profiletype'),
        ('tracks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='profile',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='track', to='profiles.profile'),
        ),
    ]
