# Generated by Django 5.2.7 on 2025-11-04 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_profilefollows'),
        ('tracks', '0004_track_human'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='name',
        ),
        migrations.AlterField(
            model_name='track',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='track', to='profiles.profile'),
        ),
    ]
