# Generated by Django 5.2.7 on 2025-11-30 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0007_alter_track_uuid_alter_trackattribute_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='insertdate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='trackattribute',
            name='insertdate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='trackattributeenum',
            name='insertdate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tracktype',
            name='insertdate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
