# Generated by Django 5.2.7 on 2025-12-02 17:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0015_alter_location_human_alter_location_profile'),
        ('profiles', '0017_alter_profile_human_alter_profilefollows_human_and_more'),
        ('tracks', '0008_alter_track_insertdate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='human',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='track',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='locations.location'),
        ),
        migrations.AlterField(
            model_name='track',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='track', to='profiles.profile'),
        ),
        migrations.AlterField(
            model_name='track',
            name='track_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='tracks.tracktype'),
        ),
        migrations.AlterField(
            model_name='trackattribute',
            name='attribute_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracks.trackattributeenum'),
        ),
        migrations.AlterField(
            model_name='trackattribute',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='tracks.track'),
        ),
    ]
