# Generated by Django 5.2.7 on 2025-11-09 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_postlike_human_alter_postlike_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='human_id',
            new_name='human',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='profile_id',
            new_name='profile',
        ),
    ]
