# Generated by Django 5.2.7 on 2025-11-20 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_rename_human_id_post_human_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='display_content',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
