# Generated by Django 5.2.7 on 2025-11-30 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_alter_post_uuid_alter_postlike_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='insertdate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='postlike',
            name='insertdate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
