# Generated by Django 5.2.7 on 2025-11-30 06:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0014_alter_profile_insertdate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('insertdate', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.BooleanField(default=False)),
                ('content', models.TextField()),
                ('channel_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages_in_channel', to='profiles.profile')),
                ('human', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chat_messages', to=settings.AUTH_USER_MODEL)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='chat_messages', to='profiles.profile')),
            ],
            options={
                'ordering': ['insertdate'],
            },
        ),
    ]
