# Generated by Django 5.2.7 on 2025-11-30 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0001_initial'),
        ('profiles', '0014_alter_profile_insertdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='channel_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chat_messages_in_channel', to='profiles.profile'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chat_messages', to='profiles.profile'),
        ),
    ]
