# Generated by Django 5.2.7 on 2025-10-25 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0003_alter_profile_profiletype'),
    ]

    operations = [
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('website', models.URLField(blank=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='teams', to='profiles.profile')),
            ],
        ),
    ]
