# Generated by Django 5.2.7 on 2025-10-26 22:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='teamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=100)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='members', to='teams.team')),
                ('human', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='team_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('team', 'human')},
            },
        ),
    ]
