# Generated by Django 5.2.7 on 2025-11-30 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0007_alter_team_uuid_alter_teammember_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='insertdate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='insertdate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
