# Generated by Django 5.2.7 on 2025-10-22 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='birthdate',
        ),
        migrations.AlterField(
            model_name='profile',
            name='profiletype',
            field=models.CharField(choices=[('DRIVER', 'Driver'), ('MODEL', 'Model'), ('STORE', 'Store')], max_length=30),
        ),
    ]
