# Generated by Django 5.2.7 on 2025-10-26 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_profile_profiletype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profiletype',
            field=models.CharField(choices=[('DRIVER', 'Driver'), ('MODEL', 'Model'), ('LOCATION', 'Location'), ('STORE', 'Store'), ('TRACK', 'Track'), ('CLUB', 'Club'), ('TEAM', 'Team'), ('EVENT', 'Event'), ('RACE', 'Race')], max_length=30),
        ),
    ]
