# Generated by Django 5.2.7 on 2025-11-06 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_profilefollows'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='followers_count',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='following_count',
        ),
    ]
