# Generated by Django 5.2.7 on 2025-11-09 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_remove_profile_followers_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profiletype',
            field=models.CharField(choices=[('DRIVER', 'Driver'), ('MODEL', 'Model'), ('CLUB', 'Club'), ('EVENT', 'Event'), ('LOCATION', 'Location'), ('RACE', 'Race'), ('STORE', 'Store'), ('TEAM', 'Team'), ('TRACK', 'Track')], max_length=30),
        ),
    ]
