# Generated by Django 5.2.7 on 2025-11-15 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_alter_profile_profiletype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profiletype',
            field=models.CharField(choices=[('DRIVER', 'Driver'), ('MODEL', 'Model'), ('LOCATION', 'Location'), ('RACE', 'Race'), ('TRACK', 'Track')], max_length=30),
        ),
    ]
