# Generated by Django 5.2.7 on 2025-11-29 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_alter_profile_uuid_alter_profilefollows_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profiletype',
            field=models.CharField(choices=[('DRIVER', 'Driver'), ('MODEL', 'Model'), ('LOCATION', 'Location'), ('TRACK', 'Track'), ('RACE', 'Race'), ('CLUB', 'Club'), ('EVENT', 'Event'), ('STORE', 'Store'), ('TEAM', 'Team')], max_length=30),
        ),
    ]
