# Generated by Django 5.2.7 on 2025-11-30 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_alter_profile_profiletype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='insertdate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='profilefollows',
            name='insertdate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
