# Generated by Django 5.2.7 on 2025-11-30 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_alter_profile_insertdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='chat_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
