# Generated by Django 5.2.7 on 2025-12-20 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0017_alter_profile_human_alter_profilefollows_human_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, help_text='Optional'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, help_text='Optional', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='displayname',
            field=models.CharField(default='', help_text='Required', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='state',
            field=models.CharField(blank=True, help_text='Optional', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='website',
            field=models.URLField(blank=True, help_text='Optional'),
        ),
    ]
