# Generated by Django 5.2.7 on 2025-10-27 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RaceAttributeEnum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='race',
            old_name='event_id',
            new_name='event',
        ),
        migrations.CreateModel(
            name='RaceAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='races.race')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='race_attributes', to='races.raceattributeenum')),
            ],
            options={
                'unique_together': {('race', 'attribute')},
            },
        ),
    ]
