# Generated by Django 5.2.7 on 2025-10-27 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_clubmember'),
        ('events', '0002_eventinterest'),
        ('locations', '0006_alter_location_latitude_alter_location_longitude'),
        ('profiles', '0004_alter_profile_profiletype'),
        ('races', '0002_raceattributeenum_rename_event_id_race_event_and_more'),
        ('teams', '0002_teammember'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RaceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='race',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='races', to='clubs.club'),
        ),
        migrations.AddField(
            model_name='race',
            name='human',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='races', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='race',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='races', to='locations.location'),
        ),
        migrations.AddField(
            model_name='race',
            name='profile',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='race', to='profiles.profile'),
        ),
        migrations.AddField(
            model_name='race',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='races', to='teams.team'),
        ),
        migrations.AlterField(
            model_name='race',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='races', to='events.event'),
        ),
        migrations.AddField(
            model_name='race',
            name='race_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='races', to='races.racetype'),
        ),
    ]
