# Generated by Django 5.2.7 on 2025-10-27 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0003_racetype_race_club_race_human_race_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='race_type',
            field=models.CharField(choices=[('Laps', 'Laps'), ('Drag', 'Drag'), ('Out and back', 'Out and back'), ('Long jump', 'Long jump')], default='', max_length=30),
        ),
        migrations.DeleteModel(
            name='RaceType',
        ),
    ]
