# Generated by Django 5.2.7 on 2025-10-29 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0004_alter_race_race_type_delete_racetype'),
    ]

    operations = [
        migrations.CreateModel(
            name='LapMonitorResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField()),
                ('session_name', models.CharField(max_length=100)),
                ('session_date', models.DateTimeField()),
                ('session_kind', models.CharField(max_length=50)),
                ('session_duration', models.FloatField()),
                ('driver_id', models.UUIDField()),
                ('driver_name', models.CharField(max_length=100)),
                ('driver_transponder_id', models.CharField(max_length=50)),
                ('driver_rank', models.IntegerField()),
                ('lap_index', models.IntegerField()),
                ('lap_end_time', models.FloatField()),
                ('lap_duration', models.FloatField()),
                ('lap_kind', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Lap Monitor Result',
                'verbose_name_plural': 'Lap Monitor Results',
                'indexes': [models.Index(fields=['session_id'], name='races_lapmo_session_0b296a_idx'), models.Index(fields=['driver_id'], name='races_lapmo_driver__8e1c6a_idx')],
            },
        ),
    ]
