# Generated by Django 5.2.7 on 2025-10-29 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0005_lapmonitorresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='race_type',
            field=models.CharField(choices=[('Lap Race', 'Lap Race'), ('Drag Race', 'Drag Race'), ('Out and Back', 'Out and Back'), ('Long Jump', 'Long Jump')], default='', max_length=30),
        ),
    ]
