# Generated by Django 5.2.7 on 2025-10-31 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0006_alter_race_race_type'),
        ('tracks', '0002_track_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='races', to='tracks.track'),
        ),
    ]
