# Generated by Django 5.2.7 on 2025-10-31 18:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_club_deleted_club_insertdate_clublocation_deleted_and_more'),
        ('events', '0005_event_deleted_event_insertdate_eventinterest_deleted_and_more'),
        ('locations', '0007_location_deleted_location_insertdate_and_more'),
        ('races', '0007_race_track'),
        ('teams', '0003_team_deleted_team_insertdate_teammember_deleted_and_more'),
        ('tracks', '0003_track_deleted_track_insertdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lapmonitorresult',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lapmonitorresult',
            name='insertdate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='race',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='race',
            name='insertdate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='raceattribute',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='raceattribute',
            name='insertdate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='raceattributeenum',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='raceattributeenum',
            name='insertdate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='lapmonitorresult',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='race',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='races', to='clubs.club'),
        ),
        migrations.AlterField(
            model_name='race',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='races', to='events.event'),
        ),
        migrations.AlterField(
            model_name='race',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='race',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='races', to='locations.location'),
        ),
        migrations.AlterField(
            model_name='race',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='races', to='teams.team'),
        ),
        migrations.AlterField(
            model_name='race',
            name='track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='races', to='tracks.track'),
        ),
        migrations.AlterField(
            model_name='raceattribute',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='raceattributeenum',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
