# Generated by Django 5.2.7 on 2025-11-03 20:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_remove_profile_location_profile_city_profile_state'),
        ('races', '0008_lapmonitorresult_deleted_lapmonitorresult_insertdate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='human',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='races', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='raceattribute',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attributes', to='races.race'),
        ),
        migrations.CreateModel(
            name='RaceDriver',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('insertdate', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted', models.BooleanField(default=False)),
                ('driver', models.ForeignKey(blank=True, limit_choices_to={'profiletype': 'DRIVER'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='driver_races', to='profiles.profile')),
                ('human', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='race_humans', to=settings.AUTH_USER_MODEL)),
                ('model', models.ForeignKey(blank=True, limit_choices_to={'profiletype': 'MODEL'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='model_races', to='profiles.profile')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='race_drivers', to='races.race')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('race', 'human'), name='unique_race_driver')],
            },
        ),
    ]
