# Generated by Django 5.2.7 on 2025-11-03 20:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_remove_profile_location_profile_city_profile_state'),
        ('races', '0009_alter_race_human_alter_raceattribute_race_racedriver'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='racedriver',
            name='unique_race_driver',
        ),
        migrations.AddConstraint(
            model_name='racedriver',
            constraint=models.UniqueConstraint(fields=('race', 'human', 'driver', 'model'), name='unique_race_driver'),
        ),
    ]
