# Generated by Django 5.2.7 on 2025-11-03 23:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_remove_profile_location_profile_city_profile_state'),
        ('races', '0011_remove_racedriver_unique_race_driver_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lapmonitorresult',
            options={'verbose_name': 'LapMonitor Result', 'verbose_name_plural': 'LapMonitor Results'},
        ),
        migrations.AddField(
            model_name='lapmonitorresult',
            name='race',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, related_name='lapmonitor_results', to='races.race'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='raceattribute',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='race_attributes', to='races.raceattributeenum'),
        ),
        migrations.AlterField(
            model_name='raceattribute',
            name='race',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='races.race'),
        ),
        migrations.AlterField(
            model_name='racedriver',
            name='driver',
            field=models.ForeignKey(blank=True, limit_choices_to={'profiletype': 'DRIVER'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver_races', to='profiles.profile'),
        ),
        migrations.AlterField(
            model_name='racedriver',
            name='human',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='race_humans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='racedriver',
            name='model',
            field=models.ForeignKey(blank=True, limit_choices_to={'profiletype': 'MODEL'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='model_races', to='profiles.profile'),
        ),
        migrations.AlterField(
            model_name='racedriver',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='race_drivers', to='races.race'),
        ),
    ]
