# Generated by Django 5.2.7 on 2025-11-04 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0012_alter_lapmonitorresult_options_lapmonitorresult_race_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='lapmonitorresult',
            index=models.Index(fields=['race', 'session_id', 'driver_id', 'lap_index'], name='races_lapmo_race_id_1582dc_idx'),
        ),
    ]
