# Generated by Django 5.2.7 on 2025-11-05 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0013_lapmonitorresult_races_lapmo_race_id_1582dc_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='transponder',
            field=models.CharField(blank=True, choices=[('LapMonitor', 'LapMonitor'), ('MyLaps', 'MyLaps')], max_length=10),
        ),
    ]
