# Generated by Django 5.2.7 on 2025-11-05 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0014_race_transponder'),
    ]

    operations = [
        migrations.AddField(
            model_name='racedriver',
            name='transponder',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
