# Generated by Django 5.2.7 on 2025-11-05 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0015_racedriver_transponder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='transponder',
            field=models.CharField(blank=True, choices=[('LapMonitor', 'LapMonitor'), ('MyLaps', 'MyLaps')], max_length=10, null=True),
        ),
    ]
