# Generated by Django 5.2.7 on 2025-11-05 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0016_alter_race_transponder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='transponder',
            field=models.CharField(blank=True, choices=[('LapMonitor', 'LapMonitor'), ('MyLaps', 'MyLaps')], default='', max_length=10),
        ),
    ]
