# Generated by Django 5.2.7 on 2025-11-05 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0018_alter_race_transponder_alter_racedriver_transponder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='racedriver',
            name='transponder',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
