# Generated by Django 5.2.7 on 2025-11-05 06:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_profilefollows'),
        ('races', '0019_alter_racedriver_transponder'),
    ]

    operations = [
        migrations.CreateModel(
            name='RaceDragRaceRound',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('insertdate', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted', models.BooleanField(default=False)),
                ('winner', models.IntegerField(null=True)),
                ('model1', models.ForeignKey(limit_choices_to={'profiletype': 'MODEL'}, on_delete=django.db.models.deletion.CASCADE, related_name='lane1_races', to='profiles.profile')),
                ('model2', models.ForeignKey(limit_choices_to={'profiletype': 'MODEL'}, on_delete=django.db.models.deletion.CASCADE, related_name='lane2_races', to='profiles.profile')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='race_rounds', to='races.race')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
