# Generated by Django 5.2.7 on 2025-11-05 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_profilefollows'),
        ('races', '0020_racedragraceround'),
    ]

    operations = [
        migrations.AddField(
            model_name='racedragraceround',
            name='round_number',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='racedragraceround',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_rounds', to='profiles.profile'),
        ),
    ]
