# Generated by Django 5.2.7 on 2025-11-05 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_profilefollows'),
        ('races', '0021_racedragraceround_round_number_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RaceDragRaceRound',
            new_name='RaceDragRace',
        ),
    ]
