# Generated by Django 5.2.7 on 2025-11-05 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_profilefollows'),
        ('races', '0022_rename_racedragraceround_racedragrace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='racedragrace',
            name='model2',
            field=models.ForeignKey(blank=True, limit_choices_to={'profiletype': 'MODEL'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lane2_races', to='profiles.profile'),
        ),
    ]
