# Generated by Django 5.2.7 on 2025-11-05 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0023_alter_racedragrace_model2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='racedragrace',
            name='model1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lane1_races', to='races.racedriver'),
        ),
        migrations.AlterField(
            model_name='racedragrace',
            name='model2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lane2_races', to='races.racedriver'),
        ),
        migrations.AlterField(
            model_name='racedragrace',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_rounds', to='races.racedriver'),
        ),
    ]
