# Generated by Django 5.2.7 on 2025-11-10 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0024_alter_racedragrace_model1_alter_racedragrace_model2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='race_type',
            field=models.CharField(choices=[('Drag Race', 'Drag Race'), ('Crawler Comp', 'Crawler Comp'), ('Lap Race', 'Lap Race'), ('Out and Back', 'Out and Back'), ('Long Jump', 'Long Jump')], default='', max_length=30),
        ),
        migrations.CreateModel(
            name='RaceCrawlerRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elapsed_time', models.FloatField(blank=True, null=True)),
                ('penalty_time', models.FloatField(blank=True, null=True)),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crawler_runs', to='races.race')),
                ('racedriver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crawler_runs', to='races.racedriver')),
            ],
        ),
    ]
