# Generated by Django 5.2.7 on 2025-11-12 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0025_alter_race_race_type_racecrawlerrun'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='racecrawlerrun',
            name='penalty_time',
        ),
        migrations.AddField(
            model_name='racecrawlerrun',
            name='penalty_points',
            field=models.IntegerField(default=0),
        ),
    ]
