# Generated by Django 5.2.7 on 2025-11-13 17:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_alter_profile_profiletype'),
        ('races', '0026_remove_racecrawlerrun_penalty_time_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlerRunLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milliseconds', models.PositiveIntegerField()),
                ('label', models.CharField(max_length=255)),
                ('delta', models.IntegerField(default=0)),
                ('driver', models.ForeignKey(blank=True, limit_choices_to={'profiletype': 'DRIVER'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crawler_driver_run_logs', to='profiles.profile')),
                ('human', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crawler_human_run_logs', to=settings.AUTH_USER_MODEL)),
                ('model', models.ForeignKey(blank=True, limit_choices_to={'profiletype': 'MODEL'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crawler_model_run_logs', to='profiles.profile')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_entries', to='races.racecrawlerrun')),
            ],
            options={
                'ordering': ['milliseconds'],
            },
        ),
    ]
