# Generated by Django 5.2.7 on 2025-11-27 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0029_alter_lapmonitorresult_uuid_alter_race_uuid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='entry_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='race',
            name='race_finished',
            field=models.BooleanField(default=False),
        ),
    ]
