# Generated by Django 5.2.7 on 2025-12-02 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0031_alter_lapmonitorresult_insertdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='race_type',
            field=models.CharField(choices=[('Lap Race', 'Lap Race'), ('Drag Race', 'Drag Race'), ('Crawler Comp', 'Crawler Comp'), ('Out and Back', 'Out and Back'), ('Long Jump', 'Long Jump'), ('Top Speed', 'Top Speed'), ('Judged Event', 'Judged Event')], default='', max_length=30),
        ),
    ]
