# Generated by Django 5.2.7 on 2025-12-18 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0033_alter_race_human_alter_race_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='race_type',
            field=models.CharField(choices=[('Lap Race', 'Lap Race'), ('Drag Race', 'Drag Race'), ('Crawler Comp', 'Crawler Comp'), ('Stopwatch Race', 'Stopwatch Race'), ('Long Jump', 'Long Jump'), ('Top Speed', 'Top Speed'), ('Judged Event', 'Judged Event')], default='', max_length=30),
        ),
        migrations.CreateModel(
            name='RaceStopwatchRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elapsed_time', models.FloatField(blank=True, null=True)),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stopwatch_runs', to='races.race')),
                ('racedriver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stopwatch_runs', to='races.racedriver')),
            ],
        ),
    ]
