# Generated by Django 5.2.7 on 2025-12-19 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0035_longjumprun_topspeedrun'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topspeedrun',
            old_name='speed',
            new_name='topspeed',
        ),
    ]
