# Generated by Django 5.2.7 on 2025-12-19 18:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0036_rename_speed_topspeedrun_topspeed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='longjumprun',
            name='distance',
        ),
        migrations.AddField(
            model_name='longjumprun',
            name='feet',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999)]),
        ),
        migrations.AddField(
            model_name='longjumprun',
            name='inches',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(11)]),
        ),
        migrations.AlterField(
            model_name='topspeedrun',
            name='topspeed',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
