# Generated by Django 5.2.7 on 2025-12-22 18:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0038_judgedeventjudge_judgedeventrun'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='judgedeventjudge',
            name='human',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='race_judges', to=settings.AUTH_USER_MODEL),
        ),
    ]
