# Generated by Django 5.2.7 on 2025-12-22 19:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0039_alter_judgedeventjudge_human'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JudgedEventRunScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='judgedeventrun',
            name='judge1',
        ),
        migrations.RemoveField(
            model_name='judgedeventrun',
            name='judge2',
        ),
        migrations.RemoveField(
            model_name='judgedeventrun',
            name='judge3',
        ),
        migrations.RemoveField(
            model_name='judgedeventrun',
            name='score1',
        ),
        migrations.RemoveField(
            model_name='judgedeventrun',
            name='score2',
        ),
        migrations.RemoveField(
            model_name='judgedeventrun',
            name='score3',
        ),
        migrations.AddConstraint(
            model_name='judgedeventjudge',
            constraint=models.UniqueConstraint(fields=('race', 'human'), name='unique_judge_per_race'),
        ),
        migrations.AddField(
            model_name='judgedeventrunscore',
            name='judge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='races.judgedeventjudge'),
        ),
        migrations.AddField(
            model_name='judgedeventrunscore',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='races.judgedeventrun'),
        ),
    ]
