# Generated by Django 5.2.7 on 2025-12-22 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0040_judgedeventrunscore_remove_judgedeventrun_judge1_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='judgedeventrunscore',
            constraint=models.UniqueConstraint(fields=('run', 'judge'), name='unique_judge_per_run_score'),
        ),
    ]
