# Generated by Django 5.2.7 on 2025-12-23 01:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0041_judgedeventrunscore_unique_judge_per_run_score'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='judgedeventrunscore',
            name='judge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='race_judge_scores', to=settings.AUTH_USER_MODEL),
        ),
    ]
