# Generated by Django 5.2.7 on 2025-12-23 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0042_alter_judgedeventrunscore_judge'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='judgedeventrun',
            constraint=models.UniqueConstraint(fields=('race', 'racedriver'), name='unique_race_racedriver'),
        ),
    ]
