# Generated by Django 5.2.7 on 2025-10-26 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interests', to='events.event')),
                ('human', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event_interests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('event', 'human')},
            },
        ),
    ]
