# Generated by Django 5.2.7 on 2025-10-27 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_eventinterest'),
        ('profiles', '0004_alter_profile_profiletype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='name',
        ),
        migrations.AddField(
            model_name='event',
            name='profile',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='profiles.profile'),
        ),
    ]
