# Generated by Django 5.2.7 on 2025-11-03 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_human'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='eventdays',
        ),
        migrations.AddField(
            model_name='event',
            name='multiday',
            field=models.BooleanField(default=False),
        ),
    ]
