# Generated by Django 5.2.7 on 2025-11-03 04:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_remove_event_eventdays_event_multiday'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='eventdays',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='event',
            name='eventtime',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='event',
            name='eventdate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
