# Generated by Django 5.2.7 on 2025-11-03 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_event_eventdays_event_eventtime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='multiday',
        ),
    ]
