# Generated by Django 5.2.7 on 2025-11-05 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_remove_event_multiday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='published',
        ),
    ]
