# Generated by Django 5.2.7 on 2025-11-30 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_alter_event_uuid_alter_eventinterest_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='insertdate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='eventinterest',
            name='insertdate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
