# Generated by Django 5.2.7 on 2025-10-25 05:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0002_remove_profile_birthdate_alter_profile_profiletype'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildAttributeEnum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('human', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='builds', to=settings.AUTH_USER_MODEL)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='builds', to='profiles.profile')),
            ],
        ),
        migrations.CreateModel(
            name='BuildAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attributes', to='builds.build')),
                ('attribute_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='builds.buildattributeenum')),
            ],
        ),
    ]
