# Generated by Django 5.2.7 on 2025-11-01 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0002_build_deleted_build_insertdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildattribute',
            name='build',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='builds.build'),
        ),
    ]
