# Generated by Django 5.2.7 on 2025-11-04 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0003_alter_buildattribute_build'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='build',
            name='description',
        ),
        migrations.RemoveField(
            model_name='build',
            name='name',
        ),
    ]
