# Generated by Django 5.2.7 on 2025-11-21 13:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0004_remove_build_description_remove_build_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='buildattribute',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='buildattributeenum',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, null=True),
        ),
    ]
