# Generated by Django 5.2.7 on 2025-11-30 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0006_alter_build_uuid_alter_buildattribute_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='build',
            name='insertdate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='buildattribute',
            name='insertdate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='buildattributeenum',
            name='insertdate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
