# Generated by Django 5.2.7 on 2025-12-02 17:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0007_alter_build_insertdate_and_more'),
        ('profiles', '0017_alter_profile_human_alter_profilefollows_human_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='build',
            name='human',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='builds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='build',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='builds', to='profiles.profile'),
        ),
        migrations.AlterField(
            model_name='buildattribute',
            name='attribute_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builds.buildattributeenum'),
        ),
    ]
