# Generated by Django 5.2.7 on 2025-10-23 01:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humans', '0002_human_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='human',
            name='invitation_code',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\d{8}$', message='Must be exactly 8 digits.')]),
        ),
    ]
