# Generated by Django 5.2.7 on 2025-10-25 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humans', '0005_alter_invitation_from_human_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='human',
            name='profession',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
