# Generated by Django 5.2.7 on 2025-10-26 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humans', '0006_human_profession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='from_human',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_invitations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='to_human',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='received_invitations', to=settings.AUTH_USER_MODEL),
        ),
    ]
