# Generated by Django 5.2.7 on 2025-10-31 19:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humans', '0008_humanfriend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='humanfriend',
            name='friend_human',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='friend_of', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='humanfriend',
            name='human',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='friends', to=settings.AUTH_USER_MODEL),
        ),
    ]
