# Generated by Django 5.2.7 on 2025-11-03 07:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humans', '0009_alter_humanfriend_friend_human_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('insertdate', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted', models.BooleanField(default=False)),
                ('friend_human', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='friend_requestor', to=settings.AUTH_USER_MODEL)),
                ('human', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='friend_requestee', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('human', 'friend_human')},
            },
        ),
    ]
