# Generated by Django 5.2.7 on 2025-11-30 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humans', '0012_alter_friendrequest_uuid_alter_human_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendrequest',
            name='insertdate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='human',
            name='insertdate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='humanfriend',
            name='insertdate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='insertdate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
