# Generated by Django 5.2.7 on 2025-10-31 19:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsorclick',
            name='human',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sponsor_clicks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sponsorclick',
            name='sponsor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='clicks', to='sponsors.sponsor'),
        ),
    ]
