# Generated by Django 5.2.7 on 2025-11-30 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0004_alter_sponsor_uuid_alter_sponsorclick_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='insertdate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sponsorclick',
            name='insertdate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
