# Generated by Django 5.2.7 on 2025-11-28 21:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StripePaymentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_slug', models.CharField(max_length=100)),
                ('stripe_session_id', models.CharField(max_length=255)),
                ('stripe_payment_intent', models.CharField(blank=True, max_length=255, null=True)),
                ('amount_total', models.IntegerField(blank=True, null=True)),
                ('currency', models.CharField(default='usd', max_length=10)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
