# Generated by Django 5.2.7 on 2025-11-04 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0004_club_human'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='name',
        ),
    ]
