# Generated by Django 5.2.7 on 2025-11-09 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0005_remove_club_name'),
        ('locations', '0010_alter_location_latitude_alter_location_longitude'),
        ('profiles', '0008_alter_profile_profiletype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='club', to='profiles.profile'),
        ),
        migrations.AlterField(
            model_name='clublocation',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='clubs.club'),
        ),
        migrations.AlterField(
            model_name='clublocation',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='club_locations', to='locations.location'),
        ),
    ]
