# Generated by Django 5.2.7 on 2025-11-30 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0008_alter_club_uuid_alter_clublocation_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='insertdate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='clublocation',
            name='insertdate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='clubmember',
            name='insertdate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
