# Generated by Django 5.2.7 on 2025-10-26 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('profiles', '0003_alter_profile_profiletype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='profiles.profile'),
        ),
    ]
