# Generated by Django 5.2.7 on 2025-11-04 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0008_location_human'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='city',
        ),
        migrations.RemoveField(
            model_name='location',
            name='name',
        ),
        migrations.RemoveField(
            model_name='location',
            name='state',
        ),
        migrations.RemoveField(
            model_name='location',
            name='website',
        ),
    ]
