# Generated by Django 5.2.7 on 2025-11-09 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0009_remove_location_city_remove_location_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=20, null=True),
        ),
    ]
