# Generated by Django 5.2.7 on 2025-11-15 22:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0010_alter_location_latitude_alter_location_longitude'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='human',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='locations', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
