# Generated by Django 5.2.7 on 2025-11-21 13:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0012_location_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
