# Generated by Django 5.2.7 on 2025-11-30 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0013_alter_location_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='insertdate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
