# Generated by Django 5.2.7 on 2025-11-04 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_store_deleted_store_insertdate_alter_store_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='name',
        ),
    ]
