# Generated by Django 5.2.7 on 2025-11-21 13:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_remove_store_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, null=True),
        ),
    ]
