# Generated by Django 5.2.7 on 2025-11-30 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_alter_store_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='insertdate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
